### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by senimamsistem** [web3bothub/soniclabs-arcade-bot#13]
Status       : Error: Failed to play game: [plinko], error: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "part"
    ],
    "message": "Required"
  }
]
Waiting      : 0h 0m 29s
Game Status  :
- plinko     : Error: Failed to play game: [plinko], error: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "part"
    ],
    "message": "Required"
  }
] (0h 0m 30s)

**Comment by overtrue** [comment]
Update the code and retry.
