### ISSUE TITLE
Failed to play game

### ISSUE THREAD

**Issue by MrTimonM** [web3bothub/soniclabs-arcade-bot#15]
Status       : Error: Failed to play game: [plinko], error: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "part"
    ],
    "message": "Required"
  }
]
Waiting      : 0h 0m 23s
Game Status  :
- plinko     : Error: Failed to play game: [plinko], error: [
  {
    "code": "invalid_type",

**Comment by overtrue** [comment]
Thanks, I have fixed it, please update and retry.

**Comment by MrTimonM** [comment]
> Thanks, I have fixed it, please update and retry.

Thanks 👍
