### ISSUE TITLE
Gateway time out

### ISSUE THREAD

**Issue by mediaordinary** [Web3BotHub/soniclabs-arcade-bot#2]
Error: 504 - Gateway Time-out. Retrying .🙏

**Comment by overtrue** [comment]
maybe the server busy or you got something error on network

**Comment by nguyenanh29** [comment]
Failed to fetch user's points. it can't play any game

**Comment by dn9568** [comment]
i'm errir this too
Error: 504 - Gateway Time-out. Retrying

**Comment by 071415Mm** [comment]
same question

**Comment by 071415Mm** [comment]
有人解决了吗 我也是同样的问题

**Comment by overtrue** [comment]
更新到最新版试试，官方改 API 了
