### ISSUE TITLE
Eror game - singlewheel and mines

### ISSUE THREAD

**Issue by mediaordinary** [Web3BotHub/soniclabs-arcade-bot#4]
Game error - singlewheel and mines but the plinko runs.
Thanks

**Comment by overtrue** [comment]
please paste the error message

**Comment by xomno01** [comment]
Points       : today: - / total: -
Status       : Error: 500 - Internal Server Error. retrying in 60 seconds
Waiting      : 0h 0m 55s
Game Status  :
- plinko     : pending (-)
- singlewheel: pending (-)
- mines      : pending (-)
---------------------------------------------------------

when getting user points done then i get this error message

**Comment by overtrue** [comment]
@xomno01 

1. config the smart address to .env： SMART_ADDRESS
2. play each game once, and ensure that the remaining times of each game are reduced by 1.
3. update the code to the latest version (`git reset --hard && git pull`). 
4. rerun the bot.
