### ISSUE TITLE
Issue Error 500

### ISSUE THREAD

**Issue by Pro-Tik** [Web3BotHub/soniclabs-arcade-bot#6]
- Account 1
---------------------------------------------------------
Address      : 0x8279BAfE6eb30
SmartAddress : 0xF8AB37a1B5216D7C234cc2a0730298dEf2D55212
Balance      : 0.0 S
Points       : today: 42.64679999999999 / total: 42.64679999999999
Status       : Error: 429 - Too Many Requests
Waiting      : 0h 0m 7s
Game Status  :
- plinko     : Daily play count limit exceeded (0h 0m 4s)
- singlewheel: pending (-)
- mines      : Error: 429 - Too Many Requests (0h 0m 30s)
---------------------------------------------------------
- Account 2
---------------------------------------------------------
Address      : 0xfA8d4cac
SmartAddress : 0x3729f14acE168a4b77A750F61D28ffbc632Fc17e
Balance      : 0.0 S
Points       : today: - / total: -
Status       : Error: 500 - Internal Server Error. retrying in 60 seconds
Waiting      : 0h 0m 36s
Game Status  :
- plinko     : pending (-)
- singlewheel: pending (-)
- mines      : pending (-)

**Comment by overtrue** [comment]
account 2: maybe you need to play the games manually each once.

**Comment by 071415Mm** [comment]
> account 2: maybe you need to play the games manually each once.

same question . i have play games manually each one

**Comment by overtrue** [comment]
> > account 2: maybe you need to play the games manually each once.
> 
> 
> 
> same question . i have play games manually each one 

500 error is server error. it's not a logic error, maybe they are maintaining the service or the server is under excessive pressure. 

So you can try to wait and see. Because if it is a logical problem, no account will be successful.
